---
name: continue-server
version: '3.3'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.4
    container_name: meilisearch
    restart: always
    volumes:
      - meilisearch_data:/meili_data
    ports:
      - 7700:7700

  continuedev:
    image: ghcr.io/c0ldfront/continue-server:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     PIP_INDEX_URL: "http://127.0.0.1:9191/index/" # Optional
    #     PIP_TRUSTED_HOSTS: "127.0.0.1" # Optional
    container_name: continuedev
    restart: always
    environment:
      - MEILISEARCH_URL=http://meilisearch:7700
      - CONTINUE_PORT=65432
      - CONTINUE_HOST=0.0.0.0
    volumes:
      - continue_data:/home/continue/.continue
    ports:
      - 65432:65432
    depends_on:
      - meilisearch

volumes:
  continue_data: {}
  meilisearch_data: {}
