#!/usr/bin/env sh

# This is so we can get the commit into the build log of a Dangerfile runner
# These come from https://docs.docker.com/docker-cloud/builds/advanced/

# For debugging all env vars
# printenv

#  Convert the location "/Dockerfile" to "Dockerfile"
FILE=$(echo -n $BUILD_PATH | tail -c +2)

if [ -z "${DOCKER_TAG}" ]; then
  docker build --build-arg=COMMIT_SHA=$(git rev-parse --short HEAD) --build-arg=COMMIT_BRANCH=$SOURCE_BRANCH -t $IMAGE_NAME -f $FILE .
else
  docker build --build-arg=COMMIT_SHA=$(git rev-parse --short HEAD) --build-arg=COMMIT_BRANCH=$DOCKER_TAG -t $IMAGE_NAME -f $FILE .
fi